name: e2e

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: e2e (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # windows not supported by dfx
        os: [ubuntu-22.04, macos-15]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock', 'rust-toolchain.toml') }}-ci-1

      - name: Build release
        run: |
          cargo build --release --locked
          echo "$(pwd)/target/release" >> "$GITHUB_PATH"

      - name: Install dfx
        uses: dfinity/setup-dfx@main

      - name: Install coreutils (macOS)
        if: ${{ contains(matrix.os, 'macos') }}
        run: brew install coreutils

      - name: Setup Bats and bats libs
        id: setup-bats
        uses: bats-core/bats-action@4.0.0

      - name: Run e2e test
        env:
          BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
        run: timeout 2100 bats e2e/tests-quill/create_neuron.bash

  aggregate:
    name: e2e:required
    if: ${{ always() }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: check e2e test result
        if: ${{ needs.test.result != 'success' }}
        run: exit 1
